m=1000;n=1000;decay='exp';decayRate=0.02;
A=GenerateData(m,n,decay,decayRate,10);
% A=imageMatrix20000;[m,n]=size(imageMatrix20000);
% A=dataMatrix;
% [m,n]=size(dataMatrix);
% S=diag(S);
T=170;
r=20;l=T;
S=svd(A);
Phi=randn(n,T);Omega=randn(n,T);Psi=randn(T,m);
Z=A*Phi;Y=A*Omega;W=Psi*A;errList=zeros(1,T);
for s=r:T/2
    d=T-s;
    Y1=Y(:,1:s);
    W1=W(1:d,:);
    Y1=Z*Z'*Y1;
    [Q,~]=qr(Y1,'econ');
    [U,S,V]=svd((Psi(1:d,:)*Q)\W1,'econ');
    U=U(:,1:r);S=S(1:r,1:r);V=V(:,1:r);
    U=Q*U;
    errList(s)=norm(A-U*S*V','fro');
end
errList(errList<=0)=Inf;
[minVal,count]=min(errList);
s=count;
d=T-s;
    Y1=Y(:,1:s);
    W1=W(1:d,:);
    [Q,~]=qr(Y1,'econ');
    [U,S,V]=svd((Psi(1:d,:)*Q)\W1,'econ');
    U=U(:,1:r);S=S(1:r,1:r);V=V(:,1:r);