errList=zeros(2,300);
r=5;Tlist=[80,110,140,170];
sNum=[57,79,101,123];
iter=4;
T=Tlist(iter);snum=sNum(iter);
for s=r:snum
    s
    load(['dataBestT/BestT',num2str(T),'_',num2str(s),'.mat']);
    errList(1,s)=estspecnorm(dataMatrix-LowRankApprox.U*LowRankApprox.S*LowRankApprox.V')/S(r+1,r+1)-1;
    errList(2,s)=estspecnorm(dataMatrix-LowRankApprox1.U*LowRankApprox1.S*LowRankApprox1.V')/S(r+1,r+1)-1;
end
%%
errList(errList<=0)=Inf;
[minSPI,count]=min(errList(1,:));
[minTYUC17,count2]=min(errList(2,:));
load(['dataBestT/BestT',num2str(T),'_',num2str(count),'.mat']);
minSPIS=estspecnorm(dataMatrix-LowRankApprox.U*LowRankApprox.S*LowRankApprox.V')/S(r+1,r+1)-1;
leftSPISpec=estspecnorm(dataMatrix-LowRankApprox.U*(LowRankApprox.U'*dataMatrix))/S(r+1,r+1)-1;
rightSPISpec=estspecnorm(LowRankApprox.U*(LowRankApprox.U'*dataMatrix)-LowRankApprox.U*LowRankApprox.S*LowRankApprox.V')/S(r+1,r+1);
load(['dataBestT/BestT',num2str(T),'_',num2str(count2),'.mat']);
minTYUC17S=estspecnorm(dataMatrix-LowRankApprox1.U*LowRankApprox1.S*LowRankApprox1.V')/S(r+1,r+1)-1;
leftTYUCSpec=estspecnorm(dataMatrix-LowRankApprox1.U*(LowRankApprox1.U'*dataMatrix))/S(r+1,r+1)-1;
rightTYUCSpec=estspecnorm(LowRankApprox1.U*(LowRankApprox1.U'*dataMatrix)-LowRankApprox1.U*LowRankApprox1.S*LowRankApprox1.V')/S(r+1,r+1);
minSPIS
leftSPISpec
rightSPISpec
minTYUC17S
leftTYUCSpec
rightTYUCSpec